# Generated by Django 3.0.6 on 2020-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='rating_restorant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
