# Generated by Django 3.0.6 on 2020-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restorant_rating_restorant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='rescription_restorant',
            field=models.CharField(max_length=200),
        ),
    ]
